AST-99809: fix ci

diff --git a/.github/workflows/build-wheels.yml b/.github/workflows/build-wheels.yml
--- a/.github/workflows/build-wheels.yml
+++ b/.github/workflows/build-wheels.yml
@@ -1,105 +1,105 @@
-name: build wheels
-
-on:
-  release:
-    types: [released]
-
-jobs:
-  enforce_stable_semver:
-    name: Require Stable Release Semver
-    runs-on: ubuntu-24.04
-    outputs:
-      version: ${{ steps.parse.outputs.version }}
-    steps:
-      - name: Parse Release Version
-        id: parse
-        shell: bash
-        run: |
-          if [[ "${GITHUB_REF_NAME}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
-            echo "GITHUB_REF_NAME=${GITHUB_REF_NAME} is a stable release semver ref"
-            echo "version=${GITHUB_REF_NAME#v}" | tee -a $GITHUB_OUTPUT
-          else
-            echo "GITHUB_REF_NAME=${GITHUB_REF_NAME} is not a stable release semver ref" >&2
-            exit 1
-          fi
-
-  build_wheels:
-    needs: enforce_stable_semver
-    defaults:
-      run:
-        working-directory: sdk/python/sdk/zrok
-    strategy:
-      fail-fast: false
-      matrix:
-        spec:
-          - { name: 'linux x86_64', runner: ubuntu-20.04, target: manylinux_2_27_x86_64 }
-          - { name: 'macOS x86_64', runner: macos-13, target: macosx_10_14_x86_64 }
-          - { name: 'Windows x86_64', runner: windows-2019, target: win_amd64 }
-    name: building ${{ matrix.spec.name }}
-    runs-on: ${{ matrix.spec.runner }}
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-
-      - name: Setup Python
-        uses: actions/setup-python@v5
-        with:
-          python-version: '3.x'
-
-      - name: Install Python Tools
-        run: python -m pip install -U pip setuptools
-
-      - name: Build distro
-        env:
-          ZROK_VERSION: ${{ github.event.release.tag_name }}
-          ZROK_PY_NAME: ${{ vars.ZROK_PY_NAME || null }}
-        run: |
-          python setup.py sdist
-
-      - uses: actions/upload-artifact@v4
-        if: startsWith(matrix.spec.name, 'linux')
-        with:
-          name: zrok_sdk_${{ matrix.spec.target }}
-          path: ${{ github.workspace }}/sdk/python/sdk/zrok/dist/*
-
-  publish-testpypi:
-    runs-on: ubuntu-20.04
-    needs: [ build_wheels ]
-    permissions:
-          id-token: write
-    steps:
-      - name: Download artifacts
-        uses: actions/download-artifact@v4
-        with:
-          path: ./dist
-          merge-multiple: true
-          pattern: zrok_sdk_*
-
-      - name: Publish wheels (TestPYPI)
-        uses: pypa/gh-action-pypi-publish@release/v1
-        with:
-          repository-url: https://test.pypi.org/legacy/
-          packages-dir: dist
-          skip-existing: true
-          verbose: true
-
-  publish-pypi:
-    runs-on: ubuntu-20.04
-    needs: [ publish-testpypi ]
-    permissions:
-          id-token: write
-    steps:
-      - name: Download artifacts
-        uses: actions/download-artifact@v4
-        with:
-          path: ./dist
-          merge-multiple: true
-          pattern: zrok_sdk_*
-
-      - name: Publish wheels (PyPI)
-        uses: pypa/gh-action-pypi-publish@release/v1
-        with:
-          packages-dir: dist
-          verbose: true
+#name: build wheels
+#
+#on:
+#  release:
+#    types: [released]
+#
+#jobs:
+#  enforce_stable_semver:
+#    name: Require Stable Release Semver
+#    runs-on: ubuntu-24.04
+#    outputs:
+#      version: ${{ steps.parse.outputs.version }}
+#    steps:
+#      - name: Parse Release Version
+#        id: parse
+#        shell: bash
+#        run: |
+#          if [[ "${GITHUB_REF_NAME}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+#            echo "GITHUB_REF_NAME=${GITHUB_REF_NAME} is a stable release semver ref"
+#            echo "version=${GITHUB_REF_NAME#v}" | tee -a $GITHUB_OUTPUT
+#          else
+#            echo "GITHUB_REF_NAME=${GITHUB_REF_NAME} is not a stable release semver ref" >&2
+#            exit 1
+#          fi
+#
+#  build_wheels:
+#    needs: enforce_stable_semver
+#    defaults:
+#      run:
+#        working-directory: sdk/python/sdk/zrok
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        spec:
+#          - { name: 'linux x86_64', runner: ubuntu-20.04, target: manylinux_2_27_x86_64 }
+#          - { name: 'macOS x86_64', runner: macos-13, target: macosx_10_14_x86_64 }
+#          - { name: 'Windows x86_64', runner: windows-2019, target: win_amd64 }
+#    name: building ${{ matrix.spec.name }}
+#    runs-on: ${{ matrix.spec.runner }}
+#    steps:
+#      - name: Checkout
+#        uses: actions/checkout@v4
+#        with:
+#          fetch-depth: 0
+#
+#      - name: Setup Python
+#        uses: actions/setup-python@v5
+#        with:
+#          python-version: '3.x'
+#
+#      - name: Install Python Tools
+#        run: python -m pip install -U pip setuptools
+#
+#      - name: Build distro
+#        env:
+#          ZROK_VERSION: ${{ github.event.release.tag_name }}
+#          ZROK_PY_NAME: ${{ vars.ZROK_PY_NAME || null }}
+#        run: |
+#          python setup.py sdist
+#
+#      - uses: actions/upload-artifact@v4
+#        if: startsWith(matrix.spec.name, 'linux')
+#        with:
+#          name: zrok_sdk_${{ matrix.spec.target }}
+#          path: ${{ github.workspace }}/sdk/python/sdk/zrok/dist/*
+#
+#  publish-testpypi:
+#    runs-on: ubuntu-20.04
+#    needs: [ build_wheels ]
+#    permissions:
+#          id-token: write
+#    steps:
+#      - name: Download artifacts
+#        uses: actions/download-artifact@v4
+#        with:
+#          path: ./dist
+#          merge-multiple: true
+#          pattern: zrok_sdk_*
+#
+#      - name: Publish wheels (TestPYPI)
+#        uses: pypa/gh-action-pypi-publish@release/v1
+#        with:
+#          repository-url: https://test.pypi.org/legacy/
+#          packages-dir: dist
+#          skip-existing: true
+#          verbose: true
+#
+#  publish-pypi:
+#    runs-on: ubuntu-20.04
+#    needs: [ publish-testpypi ]
+#    permissions:
+#          id-token: write
+#    steps:
+#      - name: Download artifacts
+#        uses: actions/download-artifact@v4
+#        with:
+#          path: ./dist
+#          merge-multiple: true
+#          pattern: zrok_sdk_*
+#
+#      - name: Publish wheels (PyPI)
+#        uses: pypa/gh-action-pypi-publish@release/v1
+#        with:
+#          packages-dir: dist
+#          verbose: true
